import { Button, Navbar, Text } from '@nextui-org/react';
import Head from 'next/head';
import Image from 'next/image';
import Index from '../components';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Navbar variant="floating">
          <Navbar.Brand>
            <Text b color="inherit" hideIn="xs">
              0xPay.sh
            </Text>
          </Navbar.Brand>
          <Navbar.Content hideIn="xs" variant="highlight-solid-rounded">
            <Navbar.Link href="#" isActive>
              Pay DID
            </Navbar.Link>
            <Navbar.Link href="#">Personal Trade</Navbar.Link>
            <Navbar.Link href="#">Task Pay</Navbar.Link>
          </Navbar.Content>
          <Navbar.Content>
            <Button auto rounded color={'primary'}>
              Connect Wallet
            </Button>
          </Navbar.Content>
        </Navbar> */}
        <Index />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
